var mongoose = require('mongoose');
var Schema = mongoose.Schema;
require('./util');

var productSchema = new Schema({
    _id: mongoose.Schema.Types.ObjectId,
    name: {type: String},
	productImage: {type: String},
	category: {type: String},
    description: {type: String},
	cart: {type: String},
	
	hasSizes: {type: String},
	//hasColors: {type:String},
	//hasPrice: {type:String},
	onSale: {type: String},
	
    masterPrice: {type: Number},
	masterSalePrice: {type: Number},
	priceS: {type: Number},
	priceM: {type: Number},
	priceL: {type: Number},
	priceXL: {type: Number},
	price2XL: {type: Number},
	price3XL: {type: Number},
	price4XL: {type: Number},
	salePriceS: {type: Number},
	salePriceM: {type: Number},
	salePriceL: {type: Number},
	salePriceXL: {type: Number},
	salePrice2XL: {type: Number},
	salePrice3XL: {type: Number},
	salePrice4XL: {type: Number},
	
	inStoreCork: {type: String},
	inStoreKala: {type: String},
	inStoreGalway: {type: String},
	inWarehouse: {type: String},
	
	totalKala: {type: Number},
	totalCork: {type: Number},
	totalGalway: {type: Number},
	totalWarehouse: {type: Number},
	
	CorkSizeS:{type: Number},
	CorkSizeM:{type: Number},
	CorkSizeL:{type: Number},
	CorkSizeXL:{type: Number},
	CorkSize2XL:{type: Number},
	CorkSize3XL:{type: Number},
	CorkSize4XL:{type: Number},
	
    KalaSizeS:{type: Number},
	KalaSizeM:{type: Number},
	KalaSizeL:{type: Number},
	KalaSizeXL:{type: Number},
	KalaSize2XL:{type: Number},
	KalaSize3XL:{type: Number},
	KalaSize4XL:{type: Number},
	
	GalwaySizeS:{type: Number},
	GalwaySizeM:{type: Number},
	GalwaySizeL:{type: Number},
	GalwaySizeXL:{type: Number},
	GalwaySize2XL:{type: Number},
	GalwaySize3XL:{type: Number},
	GalwaySize4XL:{type: Number},
	
	WarehouseSizeS:{type: Number},
	WarehouseSizeM:{type: Number},
	WarehouseSizeL:{type: Number},
	WarehouseSizeXL:{type: Number},
	WarehouseSize2XL:{type: Number},
	WarehouseSize3XL:{type: Number},
	WarehouseSize4XL:{type: Number},
	
	numColors: {type: Number},
	
	colorCode1: {type:String},
	colorCode2: {type:String},
	colorCode3: {type:String},
	colorCode4: {type:String},
	colorCode5: {type:String},
	colorCode6: {type:String},
	colorCode7: {type:String},
	colorCode8: {type:String},
	colorCode9: {type:String},
	colorCode10: {type:String},
	
	color1CorkSizeS:{type: Number},
	color1CorkSizeM:{type: Number},
	color1CorkSizeL:{type: Number},
	color1CorkSizeXL:{type: Number},
	color1CorkSize2XL:{type: Number},
	color1CorkSize3XL:{type: Number},
	color1CorkSize4XL:{type: Number},
	
    color1KalaSizeS:{type: Number},
	color1KalaSizeM:{type: Number},
	color1KalaSizeL:{type: Number},
	color1KalaSizeXL:{type: Number},
	color1KalaSize2XL:{type: Number},
	color1KalaSize3XL:{type: Number},
	color1KalaSize4XL:{type: Number},
	
	color1GalwaySizeS:{type: Number},
	color1GalwaySizeM:{type: Number},
	color1GalwaySizeL:{type: Number},
	color1GalwaySizeXL:{type: Number},
	color1GalwaySize2XL:{type: Number},
	color1GalwaySize3XL:{type: Number},
	color1GalwaySize4XL:{type: Number},
	
	color1WarehouseSizeS:{type: Number},
	color1WarehouseSizeM:{type: Number},
	color1WarehouseSizeL:{type: Number},
	color1WarehouseSizeXL:{type: Number},
	color1WarehouseSize2XL:{type: Number},
	color1WarehouseSize3XL:{type: Number},
	color1WarehouseSize4XL:{type: Number},
	
	color1Total: {type:Number},
	color1CorkTotal: {type:Number},
	color1KalaTotal: {type:Number},
	color1GalwayTotal: {type:Number},
	color1WarehouseTotal: {type:Number},
	
	color2CorkSizeS:{type: Number},
	color2CorkSizeM:{type: Number},
	color2CorkSizeL:{type: Number},
	color2CorkSizeXL:{type: Number},
	color2CorkSize2XL:{type: Number},
	color2CorkSize3XL:{type: Number},
	color2CorkSize4XL:{type: Number},
	
    color2KalaSizeS:{type: Number},
	color2KalaSizeM:{type: Number},
	color2KalaSizeL:{type: Number},
	color2KalaSizeXL:{type: Number},
	color2KalaSize2XL:{type: Number},
	color2KalaSize3XL:{type: Number},
	color2KalaSize4XL:{type: Number},
	
	color2GalwaySizeS:{type: Number},
	color2GalwaySizeM:{type: Number},
	color2GalwaySizeL:{type: Number},
	color2GalwaySizeXL:{type: Number},
	color2GalwaySize2XL:{type: Number},
	color2GalwaySize3XL:{type: Number},
	color2GalwaySize4XL:{type: Number},
	
	color2WarehouseSizeS:{type: Number},
	color2WarehouseSizeM:{type: Number},
	color2WarehouseSizeL:{type: Number},
	color2WarehouseSizeXL:{type: Number},
	color2WarehouseSize2XL:{type: Number},
	color2WarehouseSize3XL:{type: Number},
	color2WarehouseSize4XL:{type: Number},
	
	color2Total: {type:Number},
	color2CorkTotal: {type:Number},
	color2KalaTotal: {type:Number},
	color2GalwayTotal: {type:Number},
	color2WarehouseTotal: {type:Number},
	
	color3CorkSizeS:{type: Number},
	color3CorkSizeM:{type: Number},
	color3CorkSizeL:{type: Number},
	color3CorkSizeXL:{type: Number},
	color3CorkSize2XL:{type: Number},
	color3CorkSize3XL:{type: Number},
	color3CorkSize4XL:{type: Number},
	
    color3KalaSizeS:{type: Number},
	color3KalaSizeM:{type: Number},
	color3KalaSizeL:{type: Number},
	color3KalaSizeXL:{type: Number},
	color3KalaSize2XL:{type: Number},
	color3KalaSize3XL:{type: Number},
	color3KalaSize4XL:{type: Number},
	
	color3GalwaySizeS:{type: Number},
	color3GalwaySizeM:{type: Number},
	color3GalwaySizeL:{type: Number},
	color3GalwaySizeXL:{type: Number},
	color3GalwaySize2XL:{type: Number},
	color3GalwaySize3XL:{type: Number},
	color3GalwaySize4XL:{type: Number},
	
	color3WarehouseSizeS:{type: Number},
	color3WarehouseSizeM:{type: Number},
	color3WarehouseSizeL:{type: Number},
	color3WarehouseSizeXL:{type: Number},
	color3WarehouseSize2XL:{type: Number},
	color3WarehouseSize3XL:{type: Number},
	color3WarehouseSize4XL:{type: Number},
	
	color3Total: {type:Number},
	color3CorkTotal: {type:Number},
	color3KalaTotal: {type:Number},
	color3GalwayTotal: {type:Number},
	color3WarehouseTotal: {type:Number},
	
	color4CorkSizeS:{type: Number},
	color4CorkSizeM:{type: Number},
	color4CorkSizeL:{type: Number},
	color4CorkSizeXL:{type: Number},
	color4CorkSize2XL:{type: Number},
	color4CorkSize3XL:{type: Number},
	color4CorkSize4XL:{type: Number},
	
    color4KalaSizeS:{type: Number},
	color4KalaSizeM:{type: Number},
	color4KalaSizeL:{type: Number},
	color4KalaSizeXL:{type: Number},
	color4KalaSize2XL:{type: Number},
	color4KalaSize3XL:{type: Number},
	color4KalaSize4XL:{type: Number},
	
	color4GalwaySizeS:{type: Number},
	color4GalwaySizeM:{type: Number},
	color4GalwaySizeL:{type: Number},
	color4GalwaySizeXL:{type: Number},
	color4GalwaySize2XL:{type: Number},
	color4GalwaySize3XL:{type: Number},
	color4GalwaySize4XL:{type: Number},
	
	color4WarehouseSizeS:{type: Number},
	color4WarehouseSizeM:{type: Number},
	color4WarehouseSizeL:{type: Number},
	color4WarehouseSizeXL:{type: Number},
	color4WarehouseSize2XL:{type: Number},
	color4WarehouseSize3XL:{type: Number},
	color4WarehouseSize4XL:{type: Number},
	
	color4Total: {type:Number},
	color4CorkTotal: {type:Number},
	color4KalaTotal: {type:Number},
	color4GalwayTotal: {type:Number},
	color4WarehouseTotal: {type:Number},
	
	color5CorkSizeS:{type: Number},
	color5CorkSizeM:{type: Number},
	color5CorkSizeL:{type: Number},
	color5CorkSizeXL:{type: Number},
	color5CorkSize2XL:{type: Number},
	color5CorkSize3XL:{type: Number},
	color5CorkSize4XL:{type: Number},
	
    color5KalaSizeS:{type: Number},
	color5KalaSizeM:{type: Number},
	color5KalaSizeL:{type: Number},
	color5KalaSizeXL:{type: Number},
	color5KalaSize2XL:{type: Number},
	color5KalaSize3XL:{type: Number},
	color5KalaSize4XL:{type: Number},
	
	color5GalwaySizeS:{type: Number},
	color5GalwaySizeM:{type: Number},
	color5GalwaySizeL:{type: Number},
	color5GalwaySizeXL:{type: Number},
	color5GalwaySize2XL:{type: Number},
	color5GalwaySize3XL:{type: Number},
	color5GalwaySize4XL:{type: Number},
	
	color5WarehouseSizeS:{type: Number},
	color5WarehouseSizeM:{type: Number},
	color5WarehouseSizeL:{type: Number},
	color5WarehouseSizeXL:{type: Number},
	color5WarehouseSize2XL:{type: Number},
	color5WarehouseSize3XL:{type: Number},
	color5WarehouseSize4XL:{type: Number},
	
	color5Total: {type:Number},
	color5CorkTotal: {type:Number},
	color5KalaTotal: {type:Number},
	color5GalwayTotal: {type:Number},
	color5WarehouseTotal: {type:Number},
	
	color6CorkSizeS:{type: Number},
	color6CorkSizeM:{type: Number},
	color6CorkSizeL:{type: Number},
	color6CorkSizeXL:{type: Number},
	color6CorkSize2XL:{type: Number},
	color6CorkSize3XL:{type: Number},
	color6CorkSize4XL:{type: Number},
	
    color6KalaSizeS:{type: Number},
	color6KalaSizeM:{type: Number},
	color6KalaSizeL:{type: Number},
	color6KalaSizeXL:{type: Number},
	color6KalaSize2XL:{type: Number},
	color6KalaSize3XL:{type: Number},
	color6KalaSize4XL:{type: Number},
	
	color6GalwaySizeS:{type: Number},
	color6GalwaySizeM:{type: Number},
	color6GalwaySizeL:{type: Number},
	color6GalwaySizeXL:{type: Number},
	color6GalwaySize2XL:{type: Number},
	color6GalwaySize3XL:{type: Number},
	color6GalwaySize4XL:{type: Number},
	
	color6WarehouseSizeS:{type: Number},
	color6WarehouseSizeM:{type: Number},
	color6WarehouseSizeL:{type: Number},
	color6WarehouseSizeXL:{type: Number},
	color6WarehouseSize2XL:{type: Number},
	color6WarehouseSize3XL:{type: Number},
	color6WarehouseSize4XL:{type: Number},
	
	color6Total: {type:Number},
	color6CorkTotal: {type:Number},
	color6KalaTotal: {type:Number},
	color6GalwayTotal: {type:Number},
	color6WarehouseTotal: {type:Number},
	
	color7CorkSizeS:{type: Number},
	color7CorkSizeM:{type: Number},
	color7CorkSizeL:{type: Number},
	color7CorkSizeXL:{type: Number},
	color7CorkSize2XL:{type: Number},
	color7CorkSize3XL:{type: Number},
	color7CorkSize4XL:{type: Number},
	
    color7KalaSizeS:{type: Number},
	color7KalaSizeM:{type: Number},
	color7KalaSizeL:{type: Number},
	color7KalaSizeXL:{type: Number},
	color7KalaSize2XL:{type: Number},
	color7KalaSize3XL:{type: Number},
	color7KalaSize4XL:{type: Number},
	
	color7GalwaySizeS:{type: Number},
	color7GalwaySizeM:{type: Number},
	color7GalwaySizeL:{type: Number},
	color7GalwaySizeXL:{type: Number},
	color7GalwaySize2XL:{type: Number},
	color7GalwaySize3XL:{type: Number},
	color7GalwaySize4XL:{type: Number},
	
	color7WarehouseSizeS:{type: Number},
	color7WarehouseSizeM:{type: Number},
	color7WarehouseSizeL:{type: Number},
	color7WarehouseSizeXL:{type: Number},
	color7WarehouseSize2XL:{type: Number},
	color7WarehouseSize3XL:{type: Number},
	color7WarehouseSize4XL:{type: Number},
	
	color7Total: {type:Number},
	color7CorkTotal: {type:Number},
	color7KalaTotal: {type:Number},
	color7GalwayTotal: {type:Number},
	color7WarehouseTotal: {type:Number},
	
	color8CorkSizeS:{type: Number},
	color8CorkSizeM:{type: Number},
	color8CorkSizeL:{type: Number},
	color8CorkSizeXL:{type: Number},
	color8CorkSize2XL:{type: Number},
	color8CorkSize3XL:{type: Number},
	color8CorkSize4XL:{type: Number},
	
    color8KalaSizeS:{type: Number},
	color8KalaSizeM:{type: Number},
	color8KalaSizeL:{type: Number},
	color8KalaSizeXL:{type: Number},
	color8KalaSize2XL:{type: Number},
	color8KalaSize3XL:{type: Number},
	color8KalaSize4XL:{type: Number},
	
	color8GalwaySizeS:{type: Number},
	color8GalwaySizeM:{type: Number},
	color8GalwaySizeL:{type: Number},
	color8GalwaySizeXL:{type: Number},
	color8GalwaySize2XL:{type: Number},
	color8GalwaySize3XL:{type: Number},
	color8GalwaySize4XL:{type: Number},
	
	color8WarehouseSizeS:{type: Number},
	color8WarehouseSizeM:{type: Number},
	color8WarehouseSizeL:{type: Number},
	color8WarehouseSizeXL:{type: Number},
	color8WarehouseSize2XL:{type: Number},
	color8WarehouseSize3XL:{type: Number},
	color8WarehouseSize4XL:{type: Number},
	
	color8Total: {type:Number},
	color8CorkTotal: {type:Number},
	color8KalaTotal: {type:Number},
	color8GalwayTotal: {type:Number},
	color8WarehouseTotal: {type:Number},
	
	color9CorkSizeS:{type: Number},
	color9CorkSizeM:{type: Number},
	color9CorkSizeL:{type: Number},
	color9CorkSizeXL:{type: Number},
	color9CorkSize2XL:{type: Number},
	color9CorkSize3XL:{type: Number},
	color9CorkSize4XL:{type: Number},
	
    color9KalaSizeS:{type: Number},
	color9KalaSizeM:{type: Number},
	color9KalaSizeL:{type: Number},
	color9KalaSizeXL:{type: Number},
	color9KalaSize2XL:{type: Number},
	color9KalaSize3XL:{type: Number},
	color9KalaSize4XL:{type: Number},
	
	color9GalwaySizeS:{type: Number},
	color9GalwaySizeM:{type: Number},
	color9GalwaySizeL:{type: Number},
	color9GalwaySizeXL:{type: Number},
	color9GalwaySize2XL:{type: Number},
	color9GalwaySize3XL:{type: Number},
	color9GalwaySize4XL:{type: Number},
	
	color9WarehouseSizeS:{type: Number},
	color9WarehouseSizeM:{type: Number},
	color9WarehouseSizeL:{type: Number},
	color9WarehouseSizeXL:{type: Number},
	color9WarehouseSize2XL:{type: Number},
	color9WarehouseSize3XL:{type: Number},
	color9WarehouseSize4XL:{type: Number},
	
	color9Total: {type:Number},
	color9CorkTotal: {type:Number},
	color9KalaTotal: {type:Number},
	color9GalwayTotal: {type:Number},
	color9WarehouseTotal: {type:Number},
	
	color10CorkSizeS:{type: Number},
	color10CorkSizeM:{type: Number},
	color10CorkSizeL:{type: Number},
	color10CorkSizeXL:{type: Number},
	color10CorkSize2XL:{type: Number},
	color10CorkSize3XL:{type: Number},
	color10CorkSize4XL:{type: Number},
	
    color10KalaSizeS:{type: Number},
	color10KalaSizeM:{type: Number},
	color10KalaSizeL:{type: Number},
	color10KalaSizeXL:{type: Number},
	color10KalaSize2XL:{type: Number},
	color10KalaSize3XL:{type: Number},
	color10KalaSize4XL:{type: Number},
	
	color10GalwaySizeS:{type: Number},
	color10GalwaySizeM:{type: Number},
	color10GalwaySizeL:{type: Number},
	color10GalwaySizeXL:{type: Number},
	color10GalwaySize2XL:{type: Number},
	color10GalwaySize3XL:{type: Number},
	color10GalwaySize4XL:{type: Number},
	
	color10WarehouseSizeS:{type: Number},
	color10WarehouseSizeM:{type: Number},
	color10WarehouseSizeL:{type: Number},
	color10WarehouseSizeXL:{type: Number},
	color10WarehouseSize2XL:{type: Number},
	color10WarehouseSize3XL:{type: Number},
	color10WarehouseSize4XL:{type: Number},
	
	color10Total: {type:Number},
	color10CorkTotal: {type:Number},
	color10KalaTotal: {type:Number},
	color10GalwayTotal: {type:Number},
	color10WarehouseTotal: {type:Number},
});

module.exports = mongoose.model('Product', productSchema);