var mongoose = require('mongoose');
var Schema = mongoose.Schema;
require('./util');

var productSchema = new Schema({
    _id: mongoose.Schema.Types.ObjectId,
    name: {type: String},
	productImage: {type: String},
	category: {type: String},
    description: {type: String},
	cart: {type: String},
	
	hasSizes: {type: String},
	//hasColors: {type:String},
	//hasPrice: {type:String},
	onSale: {type: String},
	
    masterPrice: {type: Number},
	masterSalePrice: {type: Number},
	priceS: {type: Number},
	priceM: {type: Number},
	priceL: {type: Number},
	priceXL: {type: Number},
	price2XL: {type: Number},
	price3XL: {type: Number},
	price4XL: {type: Number},
	salePriceS: {type: Number},
	salePriceM: {type: Number},
	salePriceL: {type: Number},
	salePriceXL: {type: Number},
	salePrice2XL: {type: Number},
	salePrice3XL: {type: Number},
	salePrice4XL: {type: Number},
	
	inWarehouse: {type: String},
	totalWarehouse: {type: Number},
	
	SizeS:{type: Number},
	SizeM:{type: Number},
	SizeL:{type: Number},
	SizeXL:{type: Number},
	Size2XL:{type: Number},
	Size3XL:{type: Number},
	Size4XL:{type: Number},
	
	numColors: {type: Number},
	
	colorCode1: {type:String},
	colorCode2: {type:String},
	colorCode3: {type:String},
	colorCode4: {type:String},
	colorCode5: {type:String},
	colorCode6: {type:String},
	colorCode7: {type:String},
	colorCode8: {type:String},
	colorCode9: {type:String},
	colorCode10: {type:String},

	color1SizeS:{type: Number},
	color1SizeM:{type: Number},
	color1SizeL:{type: Number},
	color1SizeXL:{type: Number},
	color1Size2XL:{type: Number},
	color1Size3XL:{type: Number},
	color1Size4XL:{type: Number},
	color1Total: {type:Number},

	color2SizeS:{type: Number},
	color2SizeM:{type: Number},
	color2SizeL:{type: Number},
	color2SizeXL:{type: Number},
	color2Size2XL:{type: Number},
	color2Size3XL:{type: Number},
	color2Size4XL:{type: Number},
	color2Total: {type:Number},

	color3SizeS:{type: Number},
	color3SizeM:{type: Number},
	color3SizeL:{type: Number},
	color3SizeXL:{type: Number},
	color3Size2XL:{type: Number},
	color3Size3XL:{type: Number},
	color3Size4XL:{type: Number},
	color3Total: {type:Number},

	color4SizeS:{type: Number},
	color4SizeM:{type: Number},
	color4SizeL:{type: Number},
	color4SizeXL:{type: Number},
	color4Size2XL:{type: Number},
	color4Size3XL:{type: Number},
	color4Size4XL:{type: Number},
	color4Total: {type:Number},

	color5SizeS:{type: Number},
	color5SizeM:{type: Number},
	color5SizeL:{type: Number},
	color5SizeXL:{type: Number},
	color5Size2XL:{type: Number},
	color5Size3XL:{type: Number},
	color5Size4XL:{type: Number},
	color5Total: {type:Number},

	color6SizeS:{type: Number},
	color6SizeM:{type: Number},
	color6SizeL:{type: Number},
	color6SizeXL:{type: Number},
	color6Size2XL:{type: Number},
	color6Size3XL:{type: Number},
	color6Size4XL:{type: Number},
	color6Total: {type:Number},

	color7SizeS:{type: Number},
	color7SizeM:{type: Number},
	color7SizeL:{type: Number},
	color7SizeXL:{type: Number},
	color7Size2XL:{type: Number},
	color7Size3XL:{type: Number},
	color7Size4XL:{type: Number},
	color7Total: {type:Number},

	color8SizeS:{type: Number},
	color8SizeM:{type: Number},
	color8SizeL:{type: Number},
	color8SizeXL:{type: Number},
	color8Size2XL:{type: Number},
	color8Size3XL:{type: Number},
	color8Size4XL:{type: Number},
	color8Total: {type:Number},

	color9SizeS:{type: Number},
	color9SizeM:{type: Number},
	color9SizeL:{type: Number},
	color9SizeXL:{type: Number},
	color9Size2XL:{type: Number},
	color9Size3XL:{type: Number},
	color9Size4XL:{type: Number},
	color9Total: {type:Number},

	color10SizeS:{type: Number},
	color10SizeM:{type: Number},
	color10SizeL:{type: Number},
	color10SizeXL:{type: Number},
	color10Size2XL:{type: Number},
	color10Size3XL:{type: Number},
	color10Size4XL:{type: Number},
	color10Total: {type:Number},
});

module.exports = mongoose.model('Product', productSchema);